Updating GH Action configuration

diff --git a/.github/workflows/infracost.yml b/.github/workflows/infracost.yml
--- a/.github/workflows/infracost.yml
+++ b/.github/workflows/infracost.yml
@@ -65,14 +65,13 @@ jobs:
 
       - name: Check Policies
         run: |
-          echo $(jq /tmp/policies.json)
-          # result=$(</tmp/sentinel_policy_check.json)
-          # if [ "$result" != "Pass - policy.policy" ]; then
-          #   echo -e "::error::Policy check failed:\n$result"
-          #   exit 1
-          # else
-          #   echo "::info::Policy check passed."
-          # fi
+          result=$(cat /tmp/policies.json | jq .result)
+          if [ "$result" != true ]; then
+            echo -e "::error::Policy check failed:\n$result"
+            exit 1
+          else
+            echo "::info::Policy check passed."
+          fi
 
       # See https://github.com/infracost/actions/tree/master/comment
       # for other inputs such as target-type.
